export interface Agent {
  id: string
  name: string
  element: "Fire" | "Ice" | "Electric" | "Physical" | "Ether" | "Wind"
  specialty: "Attack" | "Stun" | "Anomaly" | "Support" | "Defense"
  faction: string
  rarity: "S" | "A"
  iconUrl: string
}

export interface RosterAgent {
  agentId: string
  level: number      // 1–60
  mindscape: number  // 0–6
  coreSkill: string  // 'A' | 'B' | 'C' | 'D' | 'E' | 'F'
}

export interface WEngine {
  id: string
  name: string
  specialty: string
  rarity: "S" | "A" | "B"
  description: string
}

export interface DiscSet {
  id: string
  name: string
  twoPieceBonus: string
  fourPieceBonus: string
}

export interface Bangboo {
  id: string
  name: string
  rarity: "S" | "A"
  description: string
  iconUrl: string
}

export interface SavedComp {
  id: string
  name: string
  agentIds: string[]   // always 3
  bangbooId: string
  aiSuggestion: string // text generated by AI
  createdAt: string    // ISO string
}
